### ISSUE TITLE
Splash screen not hide 

### ISSUE THREAD

**Issue by asiermusa** [aparajita/capacitor-splash-screen#10]
hi,

Device: Xiaomi Mi 10

I followed every step of docs but I am not able to hide the splash screen after app is launched.

The method  is called but the splash screen is visible alltime and I can´t view my app.

<img width="613" alt="Captura de Pantalla 2022-11-26 a las 1 57 00" src="https://user-images.githubusercontent.com/32843723/204066845-e9f8bb93-4264-42e0-8fa8-5277fddbdc7a.png">

**Comment by asiermusa** [comment]
Sorry, I uninstalled capacitors splash screen official plugin and now it works correctly.

Thanks!

**Comment by aparajita** [comment]
That would explain it!
