### ISSUE TITLE
npm update in embedding project duplicates plugin entry in package.json and make capacitor build fail for iOS

### ISSUE THREAD

**Issue by jedilor** [aparajita/capacitor-splash-screen#2]
Hi
First of all, thank you for this great plugin!

Maybe I am making a bad usage of it but here is my problem.

In my project's package.json I added:
`"ws-capacitor-splashscreen": "git+https://github.com/aparajita/ws-capacitor-splashscreen.git"`
I could make a clone but I think the problem would be the same.

`npm install` and `ionic cap sync` are then working and the app loads and successfully deals with the plugin.

Then, I had to make a `npm update` in my project to update dependencies.

But, certainly because you still have `"name": "@capacitor/splash-screen"` in your package.json file, `npm update` duplicates the entry in my project's package.json and I obtain:
`"ws-capacitor-splashscreen": "git+https://github.com/aparajita/ws-capacitor-splashscreen.git",` (CORRECT)
`"@capacitor/splash-screen": "git+https://github.com/aparajita/ws-capacitor-splashscreen.git"` (INCORRECT)

Once I get this, `ionic cap sync` calls fail with the error:
`No podspec found for 'CapacitorSplashScreen' in '../../node_modules/@capacitor/splash-screen'`

This is due to capacitor/core which uses fixName() function to set the plugin name and identify the .podspec file.
In this case, `@capacitor/splash-screen` is transformed into `CapacitorSplashScreen` and capacitor searches for `CapacitorSplashScreen.podspec`, which does not exist.

Following your design, capacitor/core should use `ws-capacitor-splashscreen` which is transformed into `WSCapacitorSplashScreen` and capacitor searches for `WSCapacitorSplashScreen.podspec`, which is correct.

So, maybe the solution should be to set `"name": "ws-capacitor-splashscreen"` in your package.json file but once again I am potentially using your plugin the bad way.

For testing purposes, I made a clone of your repository, then changed the name in the package.json from 
`"name": "@capacitor/splash-screen"`
to
`"name": "ws-capacitor-splashscreen"`
and this is now working, npm update does not duplicate the entry anymore in my project's package.json

I hope I am clear.
Thanks for your attention.

Jérôme

**Comment by aparajita** [comment]
Salut Jérôme.

> In my project's package.json I added:
> "ws-capacitor-splashscreen": "git+https://github.com/aparajita/ws-capacitor-splashscreen.git"

Shouldn't that match the package name?

> "@capacitor/splash-screen": "git+https://github.com/aparajita/ws-capacitor-splashscreen.git"

**Comment by jedilor** [comment]
"@capacitor/splash-screen": "git+https://github.com/aparajita/ws-capacitor-splashscreen.git" cannot work because of what I explained above.
When capacitor builds for iOS (using ionic cap sync) it looks for the file named : `fixName(package name).podpspec`
In your repo, the file is WSCapacitorSplashScreen.podspec (which is equal to capacitor function fixName("ws-capacitor-splashscreen").podspec)
So, the only way for it to work is to use the `ws-capacitor-splashscreen` name.

This is the reason why it has to be "ws-capacitor-splashscreen": "git+https://github.com/aparajita/ws-capacitor-splashscreen.git" in the package.json

But there also the problem with `npm update`
I am not an npm expert but is looks like npm update uses the name field found in the package.json (@capacitor/splash-screen in your case) to install the updates. This is the reason why the npm update duplicates the entry in the package.json and why I obtain both `"ws-capacitor-splashscreen": "git+https://github.com/aparajita/ws-capacitor-splashscreen.git"
` and `"@capacitor/splash-screen": "git+https://github.com/aparajita/ws-capacitor-splashscreen.git"`

It seems that everything (`npm update` then `ionic cap sync`) work correctly if:
- `"name": "ws-capacitor-splashscreen"` is used into your package.json instead of `"name": "@capacitor/splash-screen"` 
- the embedding project package.json declares: "ws-capacitor-splashscreen": "git+https://github.com/aparajita/ws-capacitor-splashscreen.git"

**Comment by jedilor** [comment]
For information, fixName() function is called by function resolvePlugin(), which are both located in capacitor/cli/src/plugin.ts
In resolvePlugin(), the plugin will be identified like this:

```
    if (meta.capacitor) {
      return {
        id: name,
        name: fixName(name),
        version: meta.version,
        rootPath,
        repository: meta.repository,
        manifest: meta.capacitor,
      };
```

And the podfile is then built using this computed name value.

With @capacitor/splash-screen, name will be computed to CapacitorSplashScreen and it will look for   CapacitorSplashScreen.podspec which does not exist!

With ws-capacitor-splash-screen, name will be computed to WSCapacitorSplashScreen and it will look for   WSCapacitorSplashScreen.podspec which exists!

**Comment by jedilor** [comment]
Another solution if you want to use
"@capacitor/splash-screen": "git+https://github.com/aparajita/ws-capacitor-splashscreen.git",  

is to duplicate WSCapacitorSplashScreen.podspec into CapacitorSplashScreen.podspec

I have juste made the test and it works pretty well except that you need to edit the newly created CapacitorSplashScreen.podspec and change:
    s.name = 'WsCapacitorSplashscreen'
into
    s.name = 'CapacitorSplashScreen'
for a successful build

**Comment by aparajita** [comment]
Yes, that step is always necessary when changing a package name.

**Comment by jedilor** [comment]
Yes, but the cool thing with this solution is you only have to duplicate this podspec file and everything should work correctly.

**Comment by aparajita** [comment]
I shouldn't have changed the package name yet, I didn't expect people to start using it.

**Comment by jedilor** [comment]
OK don't worry, I'll deal with it on my own.
Thank you and sorry to have bothered you.

Anyway, congrats from France for your great plugin! This is a great enhancement of the legacy one!

**Comment by aparajita** [comment]
Merci! Désolé pour la confusion.
