### ISSUE TITLE
Capacitor 3 version

### ISSUE THREAD

**Issue by antonioberetini** [aparajita/capacitor-splash-screen#3]
Can we add support for Capacitor 3 please?

**Comment by aparajita** [comment]
When I switch to Capacitor 3 for my own projects, which won't happen until sometime after Capacitor 3 is in final release, I'll update all of my plugins.

At one point the Capacitor team was interested in incorporating my code into Capacitor, but they stopped communicating with me for some reason. Maybe you should encourage them to think about that again.

**Comment by antonioberetini** [comment]
I wonder why they stopped communicating. This is an important part of every app. It should be in their base package.

**Comment by aparajita** [comment]
Tell them! 😁

**Comment by antonioberetini** [comment]
Hahaha I am not in charge but I can certainly suggest 🥇

**Comment by AE1NS** [comment]
Capacitor 3 is finally released now. Are you planning to update your plugins to support it?

**Comment by aparajita** [comment]
I plan to upgrade the plugins to Capacitor 3 when I convert my apps to Capacitor 3. I can't say for sure when that will happen.

**Comment by Aarbel** [comment]
@aparajita new plans for capacitor 3 support ?

**Comment by aparajita** [comment]
Hopefully in September.

**Comment by AndreaJasper** [comment]
I wanted to ask for an update :). Splash Screen is listed on Capacitor v3 docs, but I still get this same error.

**Comment by aparajita** [comment]
I'll start working on it soon.

**Comment by ChrsCrss** [comment]
@aparajita Any updates? :)

**Comment by aparajita** [comment]
Life never quite goes the way we expect, the project for which this is meant is on hold at the moment.

**Comment by aparajita** [comment]
Funding for upgrading this plugin to Capacitor 3 is on hold until the spring, sad to say.

**Comment by aparajita** [comment]
Hey all, finally got approval to upgrade everything to Capacitor 3. New splash screen will be coming in the next few weeks, and will be published to @capacitor-community.

**Comment by LiamKarlMitchell** [comment]
Any chance of updated demo/docs when this is ready?
I'll take it for a spin, wanting to animate like a Fade in/appear of logo on a background either solid or gradient.

**Comment by aparajita** [comment]
@LiamKarlMitchell Yes, of course the demo and docs will be updated. But as far as I can see now, the API won't change.

**Comment by aparajita** [comment]
Just released! It's a major overhaul and may not be backward compatible, please read the docs.
