### ISSUE TITLE
White launchscreen on android

### ISSUE THREAD

**Issue by neonish** [aparajita/capacitor-splash-screen#5]
Hi there,

I'm currently working on getting the launchscreen to show on android.

I created a new activity called LaunchScreen / launch_screen.xml with my logo as background and added the following configuration to my `capacitor.config.json:`

```
…
"WSSplashScreen": {
        "animated": true,
        "showSpinner": true,
        "autoHide": false,
        "spinnerColor": "#e20d18",
        "android": {
          "fullscreen": true,
          "source": "launch_screen.xml"
        },
        "ios" : {
            "source" : "LaunchScreen"
        }
      }
…
```

It does work great on iOS, but Android shows a blank screen after the initial loading screen from `res/drawable/splash`. After loading the app (as seen in the console) the white screen disappears and my app is shown.

Any ideas what I'm doing wrong? I'm thankful for any kind of pointers!

**Comment by aparajita** [comment]
Unfortunately on Android there is currently no way to smoothly transition from the native splash to the capacitor splash screen. It's partly a problem with Android, partly with capacitor. I end up just leaving the native splash screen blank and hope the app loads fairly quickly.

**Comment by aparajita** [comment]
Just released v2 which uses the new Android 12 splash screen API, you won't have these problems any more — but you may have to redesign your splash screen to fit the new requirements imposed by Android.

**Comment by Pravee17** [comment]
@aparajita , I ran the demo splash screen app and the splash screen doesn't work on Android 12 and below. I see a white screen. But, it works well on devices with android 13. Any suggestions on how to integrate the plugin in devices having android 12 and below ?

**Comment by aparajita** [comment]
I recommend using @capacitor/splash-screen, I had to give up on using/maintaining this plugin.
