### ISSUE TITLE
Android import package not found

### ISSUE THREAD

**Issue by george-martinec** [aparajita/capacitor-splash-screen#6]
MainActivity.java

import com.aparajita.capacitor.splashscreen.SplashScreen;

SplashScreen not found, how to implement the package ?

**Comment by aparajita** [comment]
Either you didn't install it correctly or you didn't run `cap sync`.

**Comment by george-martinec** [comment]
`npm cap sync` fixed the problem 👍🏻 Android Studio still can't find the package (but it's a cosmetic feature)

**Comment by aparajita** [comment]
I think you mean `ionic cap sync`.

Did you install all of your packages with `npm` or `pnpm`? If you use `npm`, be sure to install  this plugin and its dependencies with `npm`.

**Comment by laberg** [comment]
I have the same problem.

Packages seemed to be installed correctly after `npm i @aparajita/capacitor-splash-screen @aparajita/capacitor-logger`

But even with `ionic cap sync` the import can still not be resolved

**Comment by aparajita** [comment]
Do those packages appear in the file list in Android Studio?

You should see these entries in `capacitor.settings.gradle`:

```
include ':aparajita-capacitor-logger'
project(':aparajita-capacitor-logger').projectDir = new File('../node_modules/@aparajita/capacitor-logger/android')

include ':aparajita-capacitor-splash-screen'
project(':aparajita-capacitor-splash-screen').projectDir = new File('../node_modules/@aparajita/capacitor-splash-screen/android')
```

And these two lines in the `dependencies` in `capacitor.build.gradle`:

```
dependencies {
    implementation project(':aparajita-capacitor-logger')
    implementation project(':aparajita-capacitor-splash-screen')
```

**Comment by laberg** [comment]
Yes everything appear as you listed

I have Capacitor 4.0.0 and Android Gradle Plugin 7.2.1

**Comment by laberg** [comment]
I managed to resolve the import by downgrading my Android Studio Gradle version from 7.4.0 to 7.3.3

**Comment by aparajita** [comment]
@laberg Android Studio only offers me up to 7.3.1 for the Android Gradle plugin version. I upgraded Gradle itself to 7.5.1 with no problem.

If Android Studio refuses to index something, you can always try File > Invalidate Caches... > Clear VCS Log Caches and Index, then Restart.

**Comment by george-martinec** [comment]
@laberg You need to run `npm run build` and then `npm cap sync`
