### ISSUE TITLE
Hiding animation cause animation flick on animated-vector (AnimatedVectorDrawable)

### ISSUE THREAD

**Issue by george-martinec** [aparajita/capacitor-splash-screen#7]
Hi,

**Device:** Pixel 5 API 31
**Description:** Using fadeOutDuration on SplashScreen.hide cause animated-vector "flick".

https://developer.android.com/reference/android/graphics/drawable/AnimatedVectorDrawable

**splashscreen_icon.xml**
```
<animated-vector
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt">
    <aapt:attr name="android:drawable">
        <vector
            android:name="vector"
            android:width="200dp"
            android:height="200dp"
            android:viewportWidth="200"
            android:viewportHeight="200">
            <path
                android:name="path"
                android:pathData="M 100 141.74 C 95.321 141.744 90.694 140.763 86.42 138.86 C 82.152 136.983 78.277 134.316 75 131 C 71.706 127.642 69.032 123.728 67.1 119.44 C 65.124 115.136 64.101 110.456 64.1 105.72 C 64.028 101.033 64.913 96.38 66.701 92.047 C 68.489 87.715 71.143 83.792 74.5 80.52 C 75.836 79.316 77.582 78.665 79.38 78.7 C 79.557 78.69 79.733 78.69 79.91 78.7 C 80.909 78.725 81.892 78.949 82.804 79.357 C 83.715 79.766 84.537 80.351 85.22 81.08 C 86.671 82.669 87.472 84.748 87.46 86.9 C 87.543 87.936 87.393 88.977 87.019 89.946 C 86.645 90.916 86.057 91.789 85.3 92.5 C 81.97 96.084 80.149 100.818 80.22 105.71 C 80.21 108.387 80.791 111.033 81.92 113.46 C 82.996 115.792 84.471 117.917 86.28 119.74 C 88.08 121.537 90.191 122.994 92.51 124.04 C 94.865 125.098 97.418 125.643 100 125.64 C 102.653 125.654 105.279 125.112 107.71 124.05 C 110.091 123.003 112.247 121.505 114.06 119.64 C 115.838 117.811 117.283 115.686 118.33 113.36 C 119.415 110.927 119.908 108.271 119.77 105.61 C 119.886 100.826 118.172 96.174 114.98 92.61 L 114.81 92.44 C 113.788 91.475 113.048 90.249 112.671 88.895 C 112.294 87.541 112.294 86.109 112.671 84.755 C 113.048 83.401 113.788 82.175 114.81 81.21 L 114.98 81.04 C 115.608 80.326 116.382 79.757 117.25 79.37 C 118.13 78.965 119.082 78.737 120.05 78.7 L 120.37 78.7 C 121.248 78.702 122.12 78.851 122.95 79.14 C 123.868 79.457 124.715 79.953 125.44 80.6 C 128.736 83.869 131.377 87.739 133.22 92 C 135.03 96.359 135.932 101.041 135.87 105.76 C 135.896 110.544 134.915 115.28 132.99 119.66 C 129.239 128.277 122.357 135.159 113.74 138.91 C 109.41 140.807 104.728 141.772 100 141.74 Z M 100.27 76.51 C 98.051 76.522 95.908 75.697 94.27 74.2 C 92.76 72.78 92 70.75 92 68 C 92.034 66.987 92.276 65.992 92.711 65.077 C 93.146 64.161 93.766 63.345 94.53 62.68 C 96.051 61.209 98.094 60.399 100.21 60.43 C 101.231 60.419 102.242 60.625 103.177 61.035 C 104.111 61.446 104.948 62.051 105.63 62.81 C 107.11 64.321 107.94 66.355 107.94 68.47 C 107.94 70.585 107.11 72.619 105.63 74.13 C 104.955 74.883 104.129 75.484 103.205 75.894 C 102.281 76.304 101.281 76.514 100.27 76.51 Z"
                android:fillColor="#ffffff"
                android:strokeWidth="1"/>
        </vector>
    </aapt:attr>
    <target android:name="path">
        <aapt:attr name="android:animation">
            <objectAnimator
                android:propertyName="fillAlpha"
                android:duration="1000"
                android:valueFrom="0"
                android:valueTo="1"
                android:valueType="floatType"
                android:interpolator="@android:anim/accelerate_interpolator"/>
        </aapt:attr>
    </target>
</animated-vector>
```

**App.vue**
```
<template>
    <ion-app>
        <ion-router-outlet />
    </ion-app>
</template>

<script lang="ts">
    import { IonApp, IonRouterOutlet } from '@ionic/vue';
    import { defineComponent } from 'vue';
    import { SplashScreen } from '@aparajita/capacitor-splash-screen'

    export default defineComponent({
        name: 'App',
        components: {
            IonApp,
            IonRouterOutlet
        },
        mounted() {
            SplashScreen.hide({
                delay: 0,
                fadeOutDuration: 250
            }).catch(console.error)
        },
    });
</script>
```

**styles.xml**
```
...
    <style name="AppTheme.NoActionBar" parent="Theme.AppCompat.DayNight.NoActionBar">
        <item name="windowActionBar">false</item>
        <item name="windowNoTitle">true</item>
        <item name="android:background">@null</item>

        <item name="android:statusBarColor">@color/splashscreen_background</item>
        <item name="android:navigationBarColor">@color/splashscreen_background</item>
    </style>

    <style name="AppTheme.NoActionBarLaunch" parent="Theme.SplashScreen">
        <item name="windowSplashScreenBackground">@color/splashscreen_background</item>
        <item name="windowSplashScreenAnimatedIcon">@drawable/splashscreen_icon</item>
        <item name="android:windowSplashScreenIconBackgroundColor" tools:targetApi="31">@color/splashscreen_background</item>
        <item name="android:windowSplashScreenBrandingImage" tools:targetApi="31">@drawable/splashscreen_logo</item>
        <item name="windowSplashScreenAnimationDuration">1000</item>

        <item name="postSplashScreenTheme">@style/AppTheme.NoActionBar</item>
    </style>
...
```

**capacitor.config.ts**
```
import { CapacitorConfig } from '@capacitor/cli';

const config: CapacitorConfig = {
    ...
    plugins: {
        SplashScreen: {
            showDuration: 1000
        }
    }
};

export default config;
```

https://user-images.githubusercontent.com/87377447/199126503-75637705-895f-47a1-985c-b14a4c5ba068.mp4

**Comment by aparajita** [comment]
Are you calling `SplashScreen.initLaunchTime()` in your MainActivity.java?

As explained in the docs, you may need to add some delay when hiding:

> When you call hide() or animate(), the web view may not have been fully rendered. If you hide too quickly, there will be a flash of the web view’s background color just before it renders. That’s why a small delay may be necessary.

You also might consider using `@null` for `android:windowSplashScreenIconBackgroundColor`. You aren't using a separate color from the splash background color.

**Comment by george-martinec** [comment]
The issue is really in fadeOut animation on the `windowSplashScreenAnimatedIcon`, because `android:windowSplashScreenBrandingImage `or instead of using `AnimatedVectorDrawable `and using only `VectorDrawable `on `windowSplashScreenAnimatedIcon `works perfectly fine. There might be an issue with required defining of `windowSplashScreenAnimationDuration `for the `windowSplashScreenAnimatedIcon` ?

I am calling the initLaunchTime
```
...
public class MainActivity extends BridgeActivity
{
	@Override
	public void onCreate(Bundle savedInstanceState) {
		SplashScreen.initLaunchTime();
		super.onCreate(savedInstanceState);
	}
}
```

**Comment by george-martinec** [comment]
As you can see, I increased all the animationDurations on 3000ms everywhere, and yet the windowSplashScreenAnimatedIcon looks like to have some default animationDuration ?

https://user-images.githubusercontent.com/87377447/199131487-c5db6ba5-22e1-41ec-9791-05c3ccacdf7b.mp4

**Comment by george-martinec** [comment]
Increased animationDurations everywhere on 10 seconds, and yet the fadeOut duration on the windowSplashScreenAnimatedIcon is like 700ms

**Comment by aparajita** [comment]
The flicker disappeared when you increased the time. That's why you need a delay when you call `hide()`.

You set the duration of the animation in the vector drawable: `android:duration="1000"`

`windowSplashScreenAnimationDuration ` is not used by Android at all. It is purely there to be read by custom animation code, which you are not using. I am using the Capacitor config `showDuration`, not that value. That's why I didn't include `windowSplashScreenAnimationDuration` in the docs.

**Comment by george-martinec** [comment]
You need windowSplashScreenAnimationDuration for the animated-vector, without you get static image. The problem I have is the fadeOut on the windowSplashScreenAnimatedIcon, it has fixed fadeOut duration somewhere. Might be default duration by android ?

**Comment by aparajita** [comment]
I wouldn't say it's a fixed value, in the original example it fades out much faster than the later examples. Rather it is fading out faster than rest of the background.

I have no control over what Android is doing there, I am telling it to fade out the entire splash view. If you want more control over the timing of the icon fade, you will have to write custom animation code.

**Comment by george-martinec** [comment]
Looks like an android bug, cause sometimes it works perfectly fine in the android studio or external device, and sometimes it flicks

**Comment by aparajita** [comment]
Did you add a delay to `hide()`?

> Looks like an android bug

Android **_is_** a bug.

You have no idea how many weeks I spent fighting that stupid OS to try to eliminate all kinds of flickering.

The only way you will be able to definitively eliminate the flickering is to write a custom fade out animation yourself.

**Comment by aparajita** [comment]
Thanks for giving my plugin a try! Hope it works out for you.
