### ISSUE TITLE
Squeezed splash screen on iOS device

### ISSUE THREAD

**Issue by fxab** [aparajita/capacitor-splash-screen#8]
Hi everyone :wave:,

I am facing a issue with my launch splash screen size on iOS devices. The system splash screen is working perfectly fine (launch screen storyboard). After it disappears I get the capacitor splash screen, in a different size, it is squeezed together on some ends.

As explained I have set up a launch screen storyboard and added the following line `SplashScreen.initLaunchTime()` to my `AppDelegate.swift`.

`capacitor.config.ts` has also been updated with the `SplashScreen` property according to the docs:
```
const config: CapacitorConfig = {
  plugins: {
    SplashScreen: {
      showDuration: 700
    }
  }
}
```

Is there anything I am missing out for my iOS configuration? Or is this a known problem, someone has a solution for?

Thank you in advance,
Felix

**_EDIT: I am using a .png image instead of a .svg as splash asset for my launch screen storyboard._**

**Comment by aparajita** [comment]
A screen recording of the launch and a screenshot of the files in your Xcode project would help

**Comment by fxab** [comment]
> A screen recording of the launch and a screenshot of the files in your Xcode project would help

Thanks for the quick reply. Here is a screen recording of the launch:

https://user-images.githubusercontent.com/22346552/200878286-92738744-29b3-489d-a881-5b65495ff514.MOV

and a screenshot of my files in Xcode:

![Screenshot 2022-11-09 at 16 53 43](https://user-images.githubusercontent.com/22346552/200878412-b0f1ec20-7398-4700-9902-65a64f9bf097.png)

**Comment by aparajita** [comment]
Very strange. Send the image to me.

**Comment by fxab** [comment]
Here is the image file: [splash-screen image.zip](https://github.com/aparajita/capacitor-splash-screen/files/9979695/splash-screen.image.zip)

I generated the splash screen assets with the following package: https://github.com/ionic-team/capacitor-assets

The assets look like this in Xcode:

![Screenshot 2022-11-10 at 10 26 43](https://user-images.githubusercontent.com/22346552/201052463-1ed6feee-c156-4d9e-b0d3-3b10456dac53.png)

**_EDIT: Actually here is the folder with the generated splash screen images using the package I mentioned before._**

[splash.zip](https://github.com/aparajita/capacitor-splash-screen/files/9979425/splash.zip)

**Comment by aparajita** [comment]
Bottom line is it's best not to use a png for a splash screen on iOS and **_can't_** use a png for a splash screen on Android. You'll be much happier using an svg as the source.

**Comment by fxab** [comment]
That makes sense. The problem for me is, for one of my apps I need a `.png` file as splash screen (it is a full screen background image). I will show you an example below. I just used the wrong one in the beginning to explain my issue (you are right, it should be no problem to use a `.svg` there with the black background).

The `.png` files on android are still working fine for me. You just can't get a full screen background, it will just display the whole image in the centered circle. I thought tho, maybe it is still possible to get it to work on iOS devices. Because the system splash screen is still working perfectly fine with my `.png` images. So I guess the background needs to be removed on iOS too, unfortunately.

Here is the video with the full background image splash screen:

https://user-images.githubusercontent.com/22346552/201301089-e52e6914-b514-4427-90df-1395c39cefbd.mov

**Comment by aparajita** [comment]
I'll take a look at why .png is being resized (technically it shouldn't be), but be aware that you are kind of violating the interface guidelines and intended purpose for splash screens. They are only meant to be a very brief branding image lasting 500-1000 ms max as something to fill the screen until the app is ready. In that amount of time a complex full screen image like you have above cannot be fully seen by the user. All their eye will really see is "CLASSIC CARD".

**Comment by danielehrhardt** [comment]
Same Issue.

**Comment by masterofevil** [comment]
Me too!

tried svg instead of png same squeezed image!

found a solution (workaround):
add iphone and ipad to image set and added assets manualy then they are shown correct !

**Comment by aparajita** [comment]
You didn't set up any constraints on the image view. Without constraints, there is zero chance it will act consistently (and correctly) across screen sizes. Not sure what version of Xcode you are using, you should definitely upgrade to 14.2.

- Open `LaunchScreen.storyboard`.
- Manually resize the splash image view to the edges of the screen, ignoring safe area.
- Click on the `Add new constraints` icon at the bottom, set all of the offsets to 0, and click on all four red bars. Do NOT check `Constrain to margins`. It should look like this:

<img width="267" alt="create constraints" src="https://user-images.githubusercontent.com/22218/209756551-fa5863a2-0fdd-48f0-b1f3-9173a1555754.png">

- Click `Add 4 constraints`. Click on the phone size chooser at the bottom and try different sizes. It should always fill the entire screen. The view hierarchy should look like this:

<img width="373" alt="launch screen" src="https://user-images.githubusercontent.com/22218/209757060-de399afe-e3a9-4da4-aae0-235d0c9a8e83.png">

That should fix the problem.

**Comment by aparajita** [comment]
I should add that iOS caches launch screens, so if you make any changes to the launch screen you may have to at least delete the app from your phone and reinstall it, and perhaps restart the phone as well.
